version: 2
jobs:
  build:
    docker:
      - image: continuumio/miniconda3:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run: conda install python=3.6
      - run: pip install aiohttp<3.0,>=2.0
      - run: pip install --requirement requirements-dev.txt
