defaults: &defaults
  docker:
    - image: continuumio/miniconda3:latest
  working_directory: ~/repo

version: 2
jobs:

  build:
    <<: *defaults
    steps:
      - checkout
      - run: conda install python=3.6
      - run: ./build-scripts/create-envfile.sh
      - run: python setup.py sdist
      - persist_to_workspace:
          root: dist
          paths:
            - .

  unittest:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: dist
      - run: conda env update --name root --file dist/environment.yml
      - run: pip install --upgrade pip
      - run: pip install --requirement requirements-dev.txt dist/*.tar.gz
      - run: flake8
      - run: pytest

  pypi:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: dist
      - run: pip install --upgrade pip
      - run: pip install twine
      - run: ./build-scripts/upload-project.sh

workflows:
  version: 2
  build-test-pypi:
    jobs:
      - build
      - unittest:
          requires:
            - build
      - pypi:
          requires:
            - unittest
          filters:
            branches:
              only: master