version: 2
jobs:
  build:
    docker:
      - image: continuumio/miniconda3:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run: conda install python=3.6
      - run: which conda
      - run: which pip
