version: 2
jobs:
  build:
    docker:
      - image: continuumio/miniconda3:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run: conda install python=3.6
      - run: mkdir -p dist
      - run: python setup.py sdist
      - run: pip install "aiohttp<3.0,>=2.0" dist/aiostorage-0.1.2.tar.gz
      - run: pip install --requirement requirements-dev.txt
      - run: pytest
