version: 2
jobs:

  build:
    docker:
      - image: continuumio/miniconda3:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run: conda install python=3.6
      - run: ./build-scripts/create-envfile.sh
      - run: python setup.py sdist
      - persist_to_workspace:
          root: dist
          paths:
            - .

  test:
    docker:
      - image: continuumio/miniconda3:latest
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: dist
      - run: conda env update --name root --file dist/environment.yml
      - run: pip install --upgrade pip
      - run: pip install --requirement requirements-dev.txt dist/aiostorage-0.1.2.tar.gz
      - run: pytest

workflows:
  version: 2
  build-test:
    jobs:
      - build
      - test:
          requires:
            - build