defaults: &defaults
  docker:
    - image: continuumio/miniconda3:latest
  working_directory: ~/repo

version: 2
jobs:

  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install Python
          command: conda install python=3.6
      - run:
          name: Create conda environment file
          command: build-scripts/create-envfile.sh
      - run:
          name: Create package distribution
          command: python setup.py sdist
      - persist_to_workspace:
          root: dist
          paths:
            - .

  unit-test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: dist
      - run:
          name: Build conda environment
          command: build-scripts/build-env.sh
      - run:
          name: Linting
          command: flake8
      - run:
          name: Unit tests
          command: pytest

  unit-test-provider-api-test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: dist
      - run:
          name: Build conda environment
          command: build-scripts/build-env.sh
      - run:
          name: Create pytest configuration
          command: echo $'[pytest]\naddopts = -vv --cov=aiostorage tests/' > custom.ini
      - run:
          name: All tests
          command: pytest -c custom.ini
      - run:
          name: Full test coverage
          command: codecov

  pypi:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: dist
      - run:
          name: Upload package
          command: build-scripts/upload-project.sh

workflows:
  version: 2
  build-test-pypi:
    jobs:
      - build
      - unit-test:
          requires:
            - build
      - unit-test-provider-api-test:
          requires:
            - unit-test
          filters:
            branches:
              only: master
      - pypi:
          requires:
            - unit-test-provider-api-test
          filters:
            branches:
              only: master
